// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v6.30.2
// source: player_character_orga_edit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gift struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gift) Reset() {
	*x = Gift{}
	mi := &file_player_character_orga_edit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gift) ProtoMessage() {}

func (x *Gift) ProtoReflect() protoreflect.Message {
	mi := &file_player_character_orga_edit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gift.ProtoReflect.Descriptor instead.
func (*Gift) Descriptor() ([]byte, []int) {
	return file_player_character_orga_edit_proto_rawDescGZIP(), []int{0}
}

func (x *Gift) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Gift) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Handicap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handicap) Reset() {
	*x = Handicap{}
	mi := &file_player_character_orga_edit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handicap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handicap) ProtoMessage() {}

func (x *Handicap) ProtoReflect() protoreflect.Message {
	mi := &file_player_character_orga_edit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handicap.ProtoReflect.Descriptor instead.
func (*Handicap) Descriptor() ([]byte, []int) {
	return file_player_character_orga_edit_proto_rawDescGZIP(), []int{1}
}

func (x *Handicap) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Handicap) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Quest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quest) Reset() {
	*x = Quest{}
	mi := &file_player_character_orga_edit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quest) ProtoMessage() {}

func (x *Quest) ProtoReflect() protoreflect.Message {
	mi := &file_player_character_orga_edit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quest.ProtoReflect.Descriptor instead.
func (*Quest) Descriptor() ([]byte, []int) {
	return file_player_character_orga_edit_proto_rawDescGZIP(), []int{2}
}

func (x *Quest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Quest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type EventPlayerCharacterOrgaEdit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=characterId,proto3" json:"characterId,omitempty"`
	PublicResume  string                 `protobuf:"bytes,2,opt,name=publicResume,proto3" json:"publicResume,omitempty"`
	Background    string                 `protobuf:"bytes,3,opt,name=background,proto3" json:"background,omitempty"`
	Gitfs         []*Gift                `protobuf:"bytes,4,rep,name=gitfs,proto3" json:"gitfs,omitempty"`
	Handicaps     []*Handicap            `protobuf:"bytes,5,rep,name=handicaps,proto3" json:"handicaps,omitempty"`
	Quests        []*Quest               `protobuf:"bytes,6,rep,name=quests,proto3" json:"quests,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPlayerCharacterOrgaEdit) Reset() {
	*x = EventPlayerCharacterOrgaEdit{}
	mi := &file_player_character_orga_edit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPlayerCharacterOrgaEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPlayerCharacterOrgaEdit) ProtoMessage() {}

func (x *EventPlayerCharacterOrgaEdit) ProtoReflect() protoreflect.Message {
	mi := &file_player_character_orga_edit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPlayerCharacterOrgaEdit.ProtoReflect.Descriptor instead.
func (*EventPlayerCharacterOrgaEdit) Descriptor() ([]byte, []int) {
	return file_player_character_orga_edit_proto_rawDescGZIP(), []int{3}
}

func (x *EventPlayerCharacterOrgaEdit) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *EventPlayerCharacterOrgaEdit) GetPublicResume() string {
	if x != nil {
		return x.PublicResume
	}
	return ""
}

func (x *EventPlayerCharacterOrgaEdit) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *EventPlayerCharacterOrgaEdit) GetGitfs() []*Gift {
	if x != nil {
		return x.Gitfs
	}
	return nil
}

func (x *EventPlayerCharacterOrgaEdit) GetHandicaps() []*Handicap {
	if x != nil {
		return x.Handicaps
	}
	return nil
}

func (x *EventPlayerCharacterOrgaEdit) GetQuests() []*Quest {
	if x != nil {
		return x.Quests
	}
	return nil
}

func (x *EventPlayerCharacterOrgaEdit) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_player_character_orga_edit_proto protoreflect.FileDescriptor

var file_player_character_orga_edit_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x5f, 0x6f, 0x72, 0x67, 0x61, 0x5f, 0x65, 0x64, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x74, 0x68, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x22, 0x3e, 0x0a,
	0x04, 0x47, 0x69, 0x66, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x42, 0x0a,
	0x08, 0x48, 0x61, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x3f, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x9c, 0x02, 0x0a, 0x1c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x61, 0x45,
	0x64, 0x69, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x52,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x63,
	0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62,
	0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x05, 0x67, 0x69, 0x74,
	0x66, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x68, 0x65, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x52, 0x05, 0x67, 0x69, 0x74, 0x66, 0x73,
	0x12, 0x31, 0x0a, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x70, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x68, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x48, 0x61, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x70, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x69, 0x63,
	0x61, 0x70, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x68, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x62, 0x65, 0x6e, 0x61, 0x75, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_player_character_orga_edit_proto_rawDescOnce sync.Once
	file_player_character_orga_edit_proto_rawDescData []byte
)

func file_player_character_orga_edit_proto_rawDescGZIP() []byte {
	file_player_character_orga_edit_proto_rawDescOnce.Do(func() {
		file_player_character_orga_edit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_character_orga_edit_proto_rawDesc), len(file_player_character_orga_edit_proto_rawDesc)))
	})
	return file_player_character_orga_edit_proto_rawDescData
}

var file_player_character_orga_edit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_player_character_orga_edit_proto_goTypes = []any{
	(*Gift)(nil),                         // 0: thekeeper.Gift
	(*Handicap)(nil),                     // 1: thekeeper.Handicap
	(*Quest)(nil),                        // 2: thekeeper.Quest
	(*EventPlayerCharacterOrgaEdit)(nil), // 3: thekeeper.EventPlayerCharacterOrgaEdit
}
var file_player_character_orga_edit_proto_depIdxs = []int32{
	0, // 0: thekeeper.EventPlayerCharacterOrgaEdit.gitfs:type_name -> thekeeper.Gift
	1, // 1: thekeeper.EventPlayerCharacterOrgaEdit.handicaps:type_name -> thekeeper.Handicap
	2, // 2: thekeeper.EventPlayerCharacterOrgaEdit.quests:type_name -> thekeeper.Quest
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_player_character_orga_edit_proto_init() }
func file_player_character_orga_edit_proto_init() {
	if File_player_character_orga_edit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_character_orga_edit_proto_rawDesc), len(file_player_character_orga_edit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_character_orga_edit_proto_goTypes,
		DependencyIndexes: file_player_character_orga_edit_proto_depIdxs,
		MessageInfos:      file_player_character_orga_edit_proto_msgTypes,
	}.Build()
	File_player_character_orga_edit_proto = out.File
	file_player_character_orga_edit_proto_goTypes = nil
	file_player_character_orga_edit_proto_depIdxs = nil
}
