// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: seed_player.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventSeedPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Handle        string                 `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSeedPlayer) Reset() {
	*x = EventSeedPlayer{}
	mi := &file_seed_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSeedPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSeedPlayer) ProtoMessage() {}

func (x *EventSeedPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_seed_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSeedPlayer.ProtoReflect.Descriptor instead.
func (*EventSeedPlayer) Descriptor() ([]byte, []int) {
	return file_seed_player_proto_rawDescGZIP(), []int{0}
}

func (x *EventSeedPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *EventSeedPlayer) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

var File_seed_player_proto protoreflect.FileDescriptor

var file_seed_player_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x73, 0x65, 0x65, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x45, 0x0a,
	0x0f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x65, 0x62, 0x65, 0x6e, 0x61, 0x75, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_seed_player_proto_rawDescOnce sync.Once
	file_seed_player_proto_rawDescData []byte
)

func file_seed_player_proto_rawDescGZIP() []byte {
	file_seed_player_proto_rawDescOnce.Do(func() {
		file_seed_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seed_player_proto_rawDesc), len(file_seed_player_proto_rawDesc)))
	})
	return file_seed_player_proto_rawDescData
}

var file_seed_player_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_seed_player_proto_goTypes = []any{
	(*EventSeedPlayer)(nil), // 0: tutorial.EventSeedPlayer
}
var file_seed_player_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seed_player_proto_init() }
func file_seed_player_proto_init() {
	if File_seed_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seed_player_proto_rawDesc), len(file_seed_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seed_player_proto_goTypes,
		DependencyIndexes: file_seed_player_proto_depIdxs,
		MessageInfos:      file_seed_player_proto_msgTypes,
	}.Build()
	File_seed_player_proto = out.File
	file_seed_player_proto_goTypes = nil
	file_seed_player_proto_depIdxs = nil
}
